# Nyoba lagi clusteringg

In [2]:
! pip install kmodes joblib

Requirement already satisfied: kmodes in c:\users\shafa dzia\appdata\local\programs\python\python310\lib\site-packages (0.12.2)
Requirement already satisfied: joblib in c:\users\shafa dzia\appdata\local\programs\python\python310\lib\site-packages (1.3.2)
Requirement already satisfied: numpy>=1.10.4 in c:\users\shafa dzia\appdata\local\programs\python\python310\lib\site-packages (from kmodes) (1.26.4)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\users\shafa dzia\appdata\local\programs\python\python310\lib\site-packages (from kmodes) (1.4.2)
Requirement already satisfied: scipy>=0.13.3 in c:\users\shafa dzia\appdata\local\programs\python\python310\lib\site-packages (from kmodes) (1.11.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\shafa dzia\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn>=0.22.0->kmodes) (3.6.0)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
#import library
import pandas as pd
import numpy as np
import joblib
from pathlib import Path

from kmodes.kmodes import KModes
from sklearn.metrics import silhouette_score

In [5]:
#path
DATA_PATH = Path("../dataset/skincare_preprocessed.csv")
OUTPUT_CLUSTERED_PATH = Path("../dataset/skincare_clustered.csv")
MODEL_DIR = Path("../models/clustering")

MODEL_DIR.mkdir(parents=True, exist_ok=True)

print("Data path:", DATA_PATH)
print("Output path:", OUTPUT_CLUSTERED_PATH)
print("Model dir:", MODEL_DIR)

Data path: ..\dataset\skincare_preprocessed.csv
Output path: ..\dataset\skincare_clustered.csv
Model dir: ..\models\clustering

In [ ]:
#load data
df = pd.read_csv(DATA_PATH)

print("Jumlah data:", len(df))
print("Jumlah kolom:", len(df.columns))
df.head()

Jumlah data: 9848
Jumlah kolom: 21

,brand,name,type,ingridients,Acne_Fighting,Acne_Trigger,Anti_Aging,Brightening,Dark_Spots,Drying,...,Hydrating,Irritating,Large_Pores,Oily,Redness,Reduces_Irritation,Rosacea,Scar,Skin_Texture,Worsen_Oily
0,The Ordinary,Glycolic Acid 7% Toning Solution,Toner,"Water,Glycolic Acid,Rosa Damascena Flower Wate...",0,1,1,1,1,1,...,0,1,1,1,0,0,1,0,1,0
1,La Roche-Posay,Toleriane Hydrating Gentle Face Cleanser,Face Cleanser,"Water,Glycerin,Pentaerythrityl Tetraethylhexan...",1,1,1,1,0,1,...,0,0,0,1,1,1,0,0,0,0
2,Youth To The People,Superfood Antioxidant Cleanser,Face Cleanser,"Water,Cocamidopropyl Hydroxysultaine,Sodium Co...",0,1,1,1,1,1,...,0,1,1,0,1,1,0,0,1,0
3,COSRX,Low pH Good Morning Gel Cleanser,Face Cleanser,"Water,Cocamidopropyl Betaine,Sodium Lauroyl Me...",0,1,0,0,0,1,...,0,1,1,1,0,1,0,0,0,0
4,La Roche-Posay,Toleriane Purifying Foaming Face Cleanser,Face Cleanser,"Water,Glycerin,Coco-Betaine,Propylene Glycol,S...",1,1,1,1,0,1,...,0,0,0,1,1,0,0,0,0,0

In [ ]:
#cek tipe data
df["type"].value_counts()

type
Moisturizer       2749
Serum             2199
Face Cleanser     1689
Sunscreen         1277
Toner              865
Exfoliator         549
Makeup Remover     520
Name: count, dtype: int64

In [10]:
#atur fitur
# fitur tambahan
feature_cols = [
    "Oily",
    "Acne_Fighting",
    "Redness",
    "Large_Pores",
    "Skin_Texture",
    "Dark_Spots",
    "Scar",
    "Anti_Aging",
    "Brightening",
    "Hydrating",
    "Eczema",
    "Rosacea"
]

# tambahan fitur tambahan sebagai informasi
info_feature_cols = [
    "Worsen_Oily",
    "Acne_Trigger",
    "Irritating",
    "Drying",
    "Reduces_Irritation"
]

In [11]:
#cek semua fitur
missing_cols = [col for col in feature_cols if col not in df.columns]

if missing_cols:
    print("Kolom yang belum ada:", missing_cols)
else:
    print("Semua fitur clustering tersedia.")

Semua fitur clustering tersedia.

In [12]:
# fungsi file aman 
def safe_filename(text):
    return text.lower().replace(" ", "_").replace("/", "_")

In [ ]:
# cari k terbaik
def find_best_k_kmodes(X, k_range=range(2, 11)):
    best_score = -1
    best_k = None
    best_model = None
    best_labels = None
    results = []

    for init_method in ["Huang", "Cao"]:
        print(f"\nInit method: {init_method}")

        for k in k_range:
            kmodes = KModes(
                n_clusters=k,
                init=init_method,
                n_init=20,
                random_state=42,
                verbose=0
            )

            labels = kmodes.fit_predict(X)

            if len(set(labels)) < 2:
                continue

            score = silhouette_score(X, labels, metric="hamming")
            cluster_counts = pd.Series(labels).value_counts()
            min_cluster_size = cluster_counts.min()

            results.append({
                "init": init_method,
                "k": k,
                "silhouette_score": score,
                "min_cluster_size": min_cluster_size
            })

            print(f"K={k} | Score={score:.4f} | Min cluster={min_cluster_size}")

            if score > best_score:
                best_score = score
                best_k = k
                best_model = kmodes
                best_labels = labels

    results_df = pd.DataFrame(results)

    return best_k, best_score, best_model, best_labels, results_df

In [14]:
#clustering per type
type_list = [
    "Serum",
    "Moisturizer",
    "Face Cleanser",
    "Sunscreen",
    "Toner",
    "Exfoliator",
    "Makeup Remover"
]

all_clustered_data = []
cluster_summary = []
all_k_results = []

for type_name in type_list:
    print("\n" + "="*80)
    print(f"CLUSTERING TYPE: {type_name}")
    print("="*80)

    df_type = df[df["type"] == type_name].copy()

    if len(df_type) == 0:
        print(f"Tidak ada data untuk type: {type_name}")
        continue

    X = df_type[feature_cols].astype(int)

    print(f"Jumlah produk: {len(df_type)}")

    best_k, best_score, best_model, best_labels, k_results_df = find_best_k_kmodes(X)

    df_type["cluster"] = best_labels
    all_clustered_data.append(df_type)

    k_results_df["type"] = type_name
    all_k_results.append(k_results_df)

    model_package = {
        "model": best_model,
        "type": type_name,
        "features": feature_cols,
        "best_k": best_k,
        "silhouette_score": best_score
    }

    model_path = MODEL_DIR / f"kmodes_{safe_filename(type_name)}.pkl"
    joblib.dump(model_package, model_path)

    cluster_summary.append({
        "type": type_name,
        "jumlah_data": len(df_type),
        "best_k": best_k,
        "silhouette_score": round(best_score, 4),
        "model_path": str(model_path)
    })

    print("\nHASIL TERBAIK")
    print("Best K:", best_k)
    print("Best Silhouette Score:", round(best_score, 4))
    print("Model tersimpan di:", model_path)

    print("\nDistribusi cluster:")
    print(df_type["cluster"].value_counts().sort_index())

================================================================================
CLUSTERING TYPE: Serum
================================================================================
Jumlah produk: 2199

Init method: Huang
K=2 | Score=0.3245 | Min cluster=1078
K=3 | Score=0.3094 | Min cluster=486
K=4 | Score=0.3786 | Min cluster=384
K=5 | Score=0.3951 | Min cluster=288
K=6 | Score=0.3775 | Min cluster=145
K=7 | Score=0.3699 | Min cluster=115
K=8 | Score=0.3702 | Min cluster=92
K=9 | Score=0.3592 | Min cluster=84
K=10 | Score=0.3622 | Min cluster=57

Init method: Cao
K=2 | Score=0.2874 | Min cluster=771
K=3 | Score=0.3046 | Min cluster=504
K=4 | Score=0.3666 | Min cluster=440
K=5 | Score=0.3079 | Min cluster=60
K=6 | Score=0.3029 | Min cluster=60
K=7 | Score=0.3218 | Min cluster=58
K=8 | Score=0.3499 | Min cluster=78
K=9 | Score=0.3032 | Min cluster=67
K=10 | Score=0.3122 | Min cluster=67

HASIL TERBAIK
Best K: 5
Best Silhouette Score: 0.3951
Model tersimpan di: ..\models\clustering\kmodes_serum.pkl

Distribusi cluster:
cluster
0    448
1    288
2    408
3    735
4    320
Name: count, dtype: int64

================================================================================
CLUSTERING TYPE: Moisturizer
================================================================================
Jumlah produk: 2749

Init method: Huang
K=2 | Score=0.3649 | Min cluster=1190
K=3 | Score=0.2950 | Min cluster=586
K=4 | Score=0.3652 | Min cluster=541
K=5 | Score=0.3909 | Min cluster=418
K=6 | Score=0.3706 | Min cluster=255
K=7 | Score=0.3514 | Min cluster=153
K=8 | Score=0.3791 | Min cluster=118
K=9 | Score=0.3356 | Min cluster=102
K=10 | Score=0.3342 | Min cluster=97

Init method: Cao
K=2 | Score=0.3505 | Min cluster=709
K=3 | Score=0.2711 | Min cluster=624
K=4 | Score=0.3349 | Min cluster=388
K=5 | Score=0.1804 | Min cluster=218
K=6 | Score=0.2439 | Min cluster=175
K=7 | Score=0.3057 | Min cluster=99
K=8 | Score=0.2668 | Min cluster=99
K=9 | Score=0.3469 | Min cluster=105
K=10 | Score=0.3088 | Min cluster=104

HASIL TERBAIK
Best K: 5
Best Silhouette Score: 0.3909
Model tersimpan di: ..\models\clustering\kmodes_moisturizer.pkl

Distribusi cluster:
cluster
0    869
1    418
2    532
3    479
4    451
Name: count, dtype: int64

================================================================================
CLUSTERING TYPE: Face Cleanser
================================================================================
Jumlah produk: 1689

Init method: Huang
K=2 | Score=0.4438 | Min cluster=577
K=3 | Score=0.4476 | Min cluster=298
K=4 | Score=0.4567 | Min cluster=245
K=5 | Score=0.3590 | Min cluster=237
K=6 | Score=0.3559 | Min cluster=154
K=7 | Score=0.3760 | Min cluster=73
K=8 | Score=0.3860 | Min cluster=86
K=9 | Score=0.4085 | Min cluster=94
K=10 | Score=0.3965 | Min cluster=32

Init method: Cao
K=2 | Score=0.4487 | Min cluster=505
K=3 | Score=0.3427 | Min cluster=220
K=4 | Score=0.2966 | Min cluster=104
K=5 | Score=0.3965 | Min cluster=103
K=6 | Score=0.3533 | Min cluster=91
K=7 | Score=0.3594 | Min cluster=17
K=8 | Score=0.3625 | Min cluster=17
K=9 | Score=0.3448 | Min cluster=17
K=10 | Score=0.3607 | Min cluster=36

HASIL TERBAIK
Best K: 4
Best Silhouette Score: 0.4567
Model tersimpan di: ..\models\clustering\kmodes_face_cleanser.pkl

Distribusi cluster:
cluster
0    245
1    912
2    251
3    281
Name: count, dtype: int64

================================================================================
CLUSTERING TYPE: Sunscreen
================================================================================
Jumlah produk: 1277

Init method: Huang
K=2 | Score=0.3101 | Min cluster=489
K=3 | Score=0.3691 | Min cluster=319
K=4 | Score=0.4153 | Min cluster=189
K=5 | Score=0.3449 | Min cluster=168
K=6 | Score=0.3641 | Min cluster=121
K=7 | Score=0.3771 | Min cluster=107
K=8 | Score=0.3666 | Min cluster=30
K=9 | Score=0.3878 | Min cluster=62
K=10 | Score=0.3665 | Min cluster=54

Init method: Cao
K=2 | Score=0.3658 | Min cluster=278
K=3 | Score=0.1668 | Min cluster=136
K=4 | Score=0.2675 | Min cluster=134
K=5 | Score=0.2980 | Min cluster=164
K=6 | Score=0.3077 | Min cluster=92
K=7 | Score=0.3011 | Min cluster=16
K=8 | Score=0.3562 | Min cluster=69
K=9 | Score=0.3353 | Min cluster=69
K=10 | Score=0.2647 | Min cluster=15

HASIL TERBAIK
Best K: 4
Best Silhouette Score: 0.4153
Model tersimpan di: ..\models\clustering\kmodes_sunscreen.pkl

Distribusi cluster:
cluster
0    271
1    568
2    189
3    249
Name: count, dtype: int64

================================================================================
CLUSTERING TYPE: Toner
================================================================================
Jumlah produk: 865

Init method: Huang
K=2 | Score=0.3988 | Min cluster=421
K=3 | Score=0.3910 | Min cluster=194
K=4 | Score=0.4166 | Min cluster=149
K=5 | Score=0.3411 | Min cluster=108
K=6 | Score=0.3444 | Min cluster=89
K=7 | Score=0.3535 | Min cluster=48
K=8 | Score=0.3535 | Min cluster=37
K=9 | Score=0.3381 | Min cluster=51
K=10 | Score=0.3507 | Min cluster=37

Init method: Cao
K=2 | Score=0.3697 | Min cluster=267
K=3 | Score=0.3708 | Min cluster=198
K=4 | Score=0.2416 | Min cluster=92
K=5 | Score=0.3555 | Min cluster=91
K=6 | Score=0.3738 | Min cluster=84
K=7 | Score=0.2642 | Min cluster=26
K=8 | Score=0.3364 | Min cluster=39
K=9 | Score=0.3428 | Min cluster=38
K=10 | Score=0.3508 | Min cluster=39

HASIL TERBAIK
Best K: 4
Best Silhouette Score: 0.4166
Model tersimpan di: ..\models\clustering\kmodes_toner.pkl

Distribusi cluster:
cluster
0    190
1    166
2    360
3    149
Name: count, dtype: int64

================================================================================
CLUSTERING TYPE: Exfoliator
================================================================================
Jumlah produk: 549

Init method: Huang
K=2 | Score=0.4585 | Min cluster=243
K=3 | Score=0.4504 | Min cluster=98
K=4 | Score=0.4013 | Min cluster=101
K=5 | Score=0.4223 | Min cluster=66
K=6 | Score=0.4491 | Min cluster=37
K=7 | Score=0.4809 | Min cluster=25
K=8 | Score=0.4784 | Min cluster=28
K=9 | Score=0.4477 | Min cluster=20
K=10 | Score=0.4534 | Min cluster=9

Init method: Cao
K=2 | Score=0.4585 | Min cluster=243
K=3 | Score=0.3994 | Min cluster=61
K=4 | Score=0.4715 | Min cluster=67
K=5 | Score=0.3871 | Min cluster=61
K=6 | Score=0.2339 | Min cluster=19
K=7 | Score=0.3683 | Min cluster=22
K=8 | Score=0.3855 | Min cluster=21
K=9 | Score=0.3563 | Min cluster=5
K=10 | Score=0.3492 | Min cluster=4

HASIL TERBAIK
Best K: 7
Best Silhouette Score: 0.4809
Model tersimpan di: ..\models\clustering\kmodes_exfoliator.pkl

Distribusi cluster:
cluster
0    126
1     42
2     83
3    152
4     37
5     25
6     84
Name: count, dtype: int64

================================================================================
CLUSTERING TYPE: Makeup Remover
================================================================================
Jumlah produk: 520

Init method: Huang
K=2 | Score=0.4896 | Min cluster=173
K=3 | Score=0.4908 | Min cluster=44
K=4 | Score=0.4187 | Min cluster=50
K=5 | Score=0.4607 | Min cluster=43
K=6 | Score=0.4734 | Min cluster=18
K=7 | Score=0.4405 | Min cluster=19
K=8 | Score=0.4845 | Min cluster=6
K=9 | Score=0.4747 | Min cluster=20
K=10 | Score=0.5144 | Min cluster=13

Init method: Cao
K=2 | Score=0.4625 | Min cluster=55
K=3 | Score=0.4284 | Min cluster=56
K=4 | Score=0.4199 | Min cluster=38
K=5 | Score=0.5264 | Min cluster=26
K=6 | Score=0.4734 | Min cluster=15
K=7 | Score=0.4604 | Min cluster=6
K=8 | Score=0.4381 | Min cluster=6
K=9 | Score=0.4311 | Min cluster=6
K=10 | Score=0.4338 | Min cluster=6

HASIL TERBAIK
Best K: 5
Best Silhouette Score: 0.5264
Model tersimpan di: ..\models\clustering\kmodes_makeup_remover.pkl

Distribusi cluster:
cluster
0    309
1     35
2     40
3     26
4    110
Name: count, dtype: int64

In [15]:
#menggabungkan hasil
df_clustered = pd.concat(all_clustered_data, ignore_index=True)

df_clustered.to_csv(OUTPUT_CLUSTERED_PATH, index=False)

cluster_summary_df = pd.DataFrame(cluster_summary)
cluster_summary_df.to_csv(MODEL_DIR / "cluster_summary.csv", index=False)

k_results_all_df = pd.concat(all_k_results, ignore_index=True)
k_results_all_df.to_csv(MODEL_DIR / "all_k_results.csv", index=False)

print("Clustering selesai.")
print("Dataset hasil clustering tersimpan di:", OUTPUT_CLUSTERED_PATH)
print("Ringkasan clustering tersimpan di:", MODEL_DIR / "cluster_summary.csv")
print("Hasil percobaan semua K tersimpan di:", MODEL_DIR / "all_k_results.csv")

display(cluster_summary_df)

Clustering selesai.
Dataset hasil clustering tersimpan di: ..\dataset\skincare_clustered.csv
Ringkasan clustering tersimpan di: ..\models\clustering\cluster_summary.csv
Hasil percobaan semua K tersimpan di: ..\models\clustering\all_k_results.csv

,type,jumlah_data,best_k,silhouette_score,model_path
0,Serum,2199,5,0.3951,..\models\clustering\kmodes_serum.pkl
1,Moisturizer,2749,5,0.3909,..\models\clustering\kmodes_moisturizer.pkl
2,Face Cleanser,1689,4,0.4567,..\models\clustering\kmodes_face_cleanser.pkl
3,Sunscreen,1277,4,0.4153,..\models\clustering\kmodes_sunscreen.pkl
4,Toner,865,4,0.4166,..\models\clustering\kmodes_toner.pkl
5,Exfoliator,549,7,0.4809,..\models\clustering\kmodes_exfoliator.pkl
6,Makeup Remover,520,5,0.5264,..\models\clustering\kmodes_makeup_remover.pkl

In [16]:
#validasi hasil clustering
print("Jumlah data hasil clustering:", len(df_clustered))
print("Jumlah cluster kosong/null:", df_clustered["cluster"].isna().sum())

print("\nJumlah produk per type:")
display(df_clustered["type"].value_counts())

print("\nJumlah cluster per type:")
display(df_clustered.groupby("type")["cluster"].nunique())

Jumlah data hasil clustering: 9848
Jumlah cluster kosong/null: 0

Jumlah produk per type:

type
Moisturizer       2749
Serum             2199
Face Cleanser     1689
Sunscreen         1277
Toner              865
Exfoliator         549
Makeup Remover     520
Name: count, dtype: int64

Jumlah cluster per type:

type
Exfoliator        7
Face Cleanser     4
Makeup Remover    5
Moisturizer       5
Serum             5
Sunscreen         4
Toner             4
Name: cluster, dtype: int64

In [17]:
#karakteristik cluster
for type_name in type_list:
    print("\n" + "="*80)
    print(f"PROFIL CLUSTER: {type_name}")
    print("="*80)

    df_type = df_clustered[df_clustered["type"] == type_name].copy()

    if len(df_type) == 0:
        continue

    cluster_profile = df_type.groupby("cluster")[feature_cols].mean().round(2)

    for cluster_id in cluster_profile.index:
        print(f"\nCluster {cluster_id}")
        top_tags = cluster_profile.loc[cluster_id].sort_values(ascending=False).head(6)
        print(top_tags)

        print("\nContoh produk:")
        contoh_produk = df_type[df_type["cluster"] == cluster_id][["brand", "name", "type"]].head(5)
        print(contoh_produk.to_string(index=False))

================================================================================
PROFIL CLUSTER: Serum
================================================================================

Cluster 0
Large_Pores    0.35
Anti_Aging     0.23
Eczema         0.23
Rosacea        0.22
Redness        0.21
Brightening    0.19
Name: 0, dtype: float64

Contoh produk:
        brand                                    name  type
  KIKO Milano                      Smart Charge Drops Serum
      Clarins    Super Restorative Remodelling Serum  Serum
   La Prairie Platinum Rare Haute-Rejuvenation Elixir Serum
     May Coop          Vine Expert Serum "Anti-Aging" Serum
Dr Botanicals        Kiwi Superfood Cooling Eye Serum Serum

Cluster 1
Anti_Aging      0.98
Brightening     0.97
Scar            0.86
Oily            0.35
Skin_Texture    0.31
Redness         0.29
Name: 1, dtype: float64

Contoh produk:
        brand                                   name  type
 The Ordinary            Azelaic Acid Suspension 10% Serum
   StriVectin Peptight™ Tightening Neck Serum Roller Serum
   La Prairie          Skin Caviar Liquid Lift Serum Serum
Ikaria Beauty             Daytime Fytó Retinol Serum Serum
       Frudia         Green Grape Pore Control Serum Serum

Cluster 2
Oily             1.00
Acne_Fighting    1.00
Brightening      1.00
Redness          0.91
Large_Pores      0.31
Anti_Aging       0.28
Name: 2, dtype: float64

Contoh produk:
          brand                                                                   name  type
        G9 Skin                                                     AC Solution Serum  Serum
      innisfree                             Moisture Plumping Serum with Lava Seawater Serum
       Numbuzin                                              No.9 Secret Firming Serum Serum
Volition Beauty Palo Azul Hydra-Bounce Pressed Serum with Niacinamide + Vegan Squalane Serum
 La Roche-Posay                            Pigmentclar Serum Visible Dark Spot Reducer Serum

Cluster 3
Anti_Aging       0.99
Brightening      0.99
Skin_Texture     0.95
Oily             0.94
Dark_Spots       0.88
Acne_Fighting    0.82
Name: 3, dtype: float64

Contoh produk:
        brand                                       name  type
The Face Shop          Dr. Belmeur Red Pro-Retinol Serum Serum
     Shiseido Vital Perfection LiftDefine Radiance Serum Serum
     Shiseido            Wrinkle Smoothing Contour Serum Serum
  Burt's Bees Vitamin C + E + F Serum with Lotus Extract Serum
     Shiseido White Lucent Illuminating Micro-Spot Serum Serum

Cluster 4
Redness         1.00
Dark_Spots      1.00
Anti_Aging      0.99
Skin_Texture    0.98
Brightening     0.90
Scar            0.26
Name: 4, dtype: float64

Contoh produk:
   brand                                            name  type
  Rodial              Pink Diamond Instant lifting Serum Serum
   Fresh  Sugar Triple-Action Lip Serum Advanced Therapy Serum
  La Mer                The Revitalizing Hydrating Serum Serum
 Kiehl's Hydro-Plumping Re-Texturizing Serum Concentrate Serum
Shiseido              Bio-Performance Glow Revival Serum Serum

================================================================================
PROFIL CLUSTER: Moisturizer
================================================================================

Cluster 0
Brightening    0.31
Eczema         0.24
Rosacea        0.23
Redness        0.20
Large_Pores    0.19
Anti_Aging     0.17
Name: 0, dtype: float64

Contoh produk:
 brand                                       name        type
 COSRX         Advanced Snail 92 All In One Cream Moisturizer
CeraVe                  Daily Moisturizing Lotion Moisturizer
 Nivea      Daily Essentials Mattifying Day Cream Moisturizer
  Ryor Denní Krém S Amarantovým Olejem A Hedvábím Moisturizer
  Ryor                     Výživný Krém Exclusive Moisturizer

Cluster 1
Anti_Aging      1.00
Brightening     0.96
Redness         0.95
Skin_Texture    0.86
Dark_Spots      0.80
Scar            0.43
Name: 1, dtype: float64

Contoh produk:
        brand                                             name        type
      L'Oreal         Age Perfect Cell Renewal Rosy Tone Cream Moisturizer
      Origins GinZing SPF40 Energy-Boosting Tinted Moisturizer Moisturizer
 Soap & Glory               In The Bright Of Day Vitamin C Gel Moisturizer
The Body Shop              Vitamin C Glow-Protect Lotion SPF30 Moisturizer
        Boots                       Collagen Day Cream SPF 30  Moisturizer

Cluster 2
Brightening    0.99
Anti_Aging     0.98
Scar           0.95
Large_Pores    0.31
Eczema         0.31
Hydrating      0.23
Name: 2, dtype: float64

Contoh produk:
       brand                                                    name        type
The Ordinary                       Natural Moisturizing Factors + HA Moisturizer
      CeraVe                                      Moisturizing Cream Moisturizer
      Missha                         M Perfect Cover BB Cream SPF 42 Moisturizer
     Lancôme Rénergie Lift Multi-Action Ultra Face Cream with SPF 30 Moisturizer
    Anna Sui                                            Moisturizer  Moisturizer

Cluster 3
Acne_Fighting    1.00
Brightening      1.00
Oily             0.99
Redness          0.91
Anti_Aging       0.44
Scar             0.28
Name: 3, dtype: float64

Contoh produk:
     brand                                                     name        type
Neutrogena                      Clear & Defend Oil-Free Moisturiser Moisturizer
  Ivatherm                                                 Ivapur K Moisturizer
   Kiehl's    Oil Eliminator 24-Hour Anti-Shine Moisturizer for Men Moisturizer
     Mizon               Acence Blemish Control Soothing Gel Cream  Moisturizer
      Olay Regenerist 3 Point Firming Anti-Ageing Cream Moisturiser Moisturizer

Cluster 4
Anti_Aging       0.99
Brightening      0.98
Oily             0.95
Large_Pores      0.93
Acne_Fighting    0.87
Skin_Texture     0.86
Name: 4, dtype: float64

Contoh produk:
    brand                     name        type
Dr. Jart+            BB Dis-A-Pore Moisturizer
  Glytone    Rejuvenating Cream 15 Moisturizer
 Proactiv    Green Tea Moisturizer Moisturizer
   Lavido Age Away Hydrating Cream Moisturizer
  Glytone    Rejuvenating Cream 20 Moisturizer

================================================================================
PROFIL CLUSTER: Face Cleanser
================================================================================

Cluster 0
Anti_Aging     0.99
Brightening    0.98
Scar           0.87
Redness        0.31
Large_Pores    0.31
Oily           0.25
Name: 0, dtype: float64

Contoh produk:
         brand                                        name          type
La Roche-Posay    Toleriane Hydrating Gentle Face Cleanser Face Cleanser
La Roche-Posay   Toleriane Purifying Foaming Face Cleanser Face Cleanser
         Nivea Daily Essentials Refreshing Facial Wash Gel Face Cleanser
    Omorovicza                         Moor Cream Cleanser Face Cleanser
          Iope               Moist Cleansing Whipping Foam Face Cleanser

Cluster 1
Large_Pores    0.38
Eczema         0.21
Rosacea        0.16
Brightening    0.15
Redness        0.14
Hydrating      0.12
Name: 1, dtype: float64

Contoh produk:
            brand                                                                     name          type
            COSRX                                         Low pH Good Morning Gel Cleanser Face Cleanser
       Jack Black                                         Pure Clean Daily Facial Cleanser Face Cleanser
            Lakme Blush & Glow Strawberry Freshness Gel Face Wash With Strawberry Extracts Face Cleanser
   King of Shaves                                                     Refreshing Face Wash Face Cleanser
Peter Thomas Roth                                                       Acne Clearing Wash Face Cleanser

Cluster 2
Anti_Aging      1.00
Brightening     0.99
Skin_Texture    0.98
Dark_Spots      0.95
Large_Pores     0.86
Oily            0.71
Name: 2, dtype: float64

Contoh produk:
              brand                                            name          type
Youth To The People                  Superfood Antioxidant Cleanser Face Cleanser
           GLAMGLOW                                   SUPERCLEANSE™ Face Cleanser
    Kate Somerville         ExfoliKate® Cleanser Daily Foaming Wash Face Cleanser
         Neutrogena Pore Refining Exfoliating Daily Facial Cleanser Face Cleanser
      PrescriptSkin                      Glycolic Acid Gel Cleanser Face Cleanser

Cluster 3
Brightening      0.99
Acne_Fighting    0.94
Oily             0.91
Large_Pores      0.88
Eczema           0.82
Redness          0.42
Name: 3, dtype: float64

Contoh produk:
         brand                                      name          type
        CeraVe                      Renewing SA Cleanser Face Cleanser
        CeraVe                   Foaming Facial Cleanser Face Cleanser
         Nivea       Men Deep Rapid Acne Clear Face Wash Face Cleanser
Logically Skin                             ACNE Cleanser Face Cleanser
       Garnier Pure Active Anti-Blackhead Deep Pore Wash Face Cleanser

================================================================================
PROFIL CLUSTER: Sunscreen
================================================================================

Cluster 0
Redness          0.99
Brightening      0.95
Oily             0.92
Acne_Fighting    0.92
Anti_Aging       0.54
Eczema           0.54
Name: 0, dtype: float64

Contoh produk:
           brand                                            name      type
Beauty of Joseon                  Relief Sun : Rice + Probiotics Sunscreen
           Sk-II Atmosphere Airy Light UV Emulsion SPF 30 PA+++  Sunscreen
            Hera         Sun Mate Airy Sun Milk SPF 50+ / PA++++ Sunscreen
         Eucerin     Daily Hydration Cream Broad Spectrum SPF 30 Sunscreen
       Dr. Jart+   Every Sun Day Moisturizing Sun SPF 50+ PA++++ Sunscreen

Cluster 1
Eczema         0.64
Rosacea        0.60
Brightening    0.58
Large_Pores    0.13
Redness        0.07
Hydrating      0.07
Name: 1, dtype: float64

Contoh produk:
               brand                                                            name      type
              A'Pieu            Pure Block Natural Waterproof Sun Cream SPF50+ PA+++ Sunscreen
Person & Covey, Inc.                                               Solbar Avo SPF 35 Sunscreen
      Kose Cosmeport Sekkisei Clear Wellness UV Sunscreen Essence Gel SPF 50+ PA++++ Sunscreen
                 VZK                           Sun Protection Cream SPF 50+ Anti-Age Sunscreen
Person & Covey, Inc.                                             Solbar Fifty SPF 50 Sunscreen

Cluster 2
Anti_Aging      1.00
Brightening     0.96
Redness         0.94
Skin_Texture    0.92
Dark_Spots      0.87
Eczema          0.65
Name: 2, dtype: float64

Contoh produk:
               brand                                 name      type
             L'Oreal UV Perfect City Resist SPF50+ PA++++ Sunscreen
            Erborian                       CC Cream Clair Sunscreen
           innisfree          Intensive Leisure Sun Stick Sunscreen
Person & Covey, Inc.  DML Daily Facial Moisturizer SPF 25 Sunscreen
           Lancaster  Sun Beauty Velvet Touch Cream SPF30 Sunscreen

Cluster 3
Scar           0.98
Anti_Aging     0.98
Brightening    0.98
Eczema         0.59
Rosacea        0.46
Large_Pores    0.12
Name: 3, dtype: float64

Contoh produk:
          brand                                                    name      type
       Skinfood                Sunflower Airy Sun Stick SPF 50+ PA++++  Sunscreen
Elizabeth Arden Eight Hour® Cream Sun Defense for Face SPF 50 Sunscreen Sunscreen
           KAHI                                 Aqua Balm SPF 50 PA++++ Sunscreen
       Shiseido        Anessa Perfect UV Sunscreen Skincare Milk (2020) Sunscreen
         Romand                    Zero Sun Clean SPF 50 PA++++ Tone Up Sunscreen

================================================================================
PROFIL CLUSTER: Toner
================================================================================

Cluster 0
Anti_Aging      1.00
Brightening     0.97
Scar            0.82
Skin_Texture    0.68
Redness         0.65
Oily            0.59
Name: 0, dtype: float64

Contoh produk:
            brand                                          name  type
          Harry's                              Post-Shave Mist  Toner
           Frudia          Pomegranate Nutri-Moisturizing Toner Toner
           Frudia                  Avocado Relief Essence Toner Toner
           ananné                      Tonicum Pore Toning Mist Toner
Rituals Cosmetics The Ritual Of Namaste Clarifying Facial Toner Toner

Cluster 1
Brightening      0.97
Oily             0.96
Acne_Fighting    0.92
Redness          0.78
Large_Pores      0.56
Eczema           0.37
Name: 1, dtype: float64

Contoh produk:
            brand                                                     name  type
Revolution Beauty                                  2% Salicylic Acid Tonic Toner
          Origins                           Zero Oil™ Pore Purifying Toner Toner
          Garnier                Organics Purifying Thyme Perfecting Toner Toner
            Payot Pâte Grise Eau Purifiante (Spot & Anti-Blemish Solution) Toner
          Kiehl's                       Milk-Peel Gentle Exfoliating Toner Toner

Cluster 2
Large_Pores    0.38
Redness        0.23
Rosacea        0.21
Hydrating      0.18
Eczema         0.16
Anti_Aging     0.14
Name: 2, dtype: float64

Contoh produk:
   brand                            name  type
Shiseido Revitalizing Treatment Softener Toner
 L'Oreal                HydraFresh Toner Toner
 Clarins         Hydrating Toning Lotion Toner
 Eucerin          ProACNE Solution Toner Toner
     VZK              Face Soothing Mist Toner

Cluster 3
Anti_Aging      1.00
Brightening     0.99
Large_Pores     0.98
Oily            0.94
Rosacea         0.91
Skin_Texture    0.79
Name: 3, dtype: float64

Contoh produk:
            brand                             name  type
     The Ordinary Glycolic Acid 7% Toning Solution Toner
Mila Moursi Paris               PH Balancing Toner Toner
     Eva Naturals       Skin Renewing Facial Toner Toner
       StriVectin       Tri-Phase Daily Glow Toner Toner
         Palmer's                Complexion Toner  Toner

================================================================================
PROFIL CLUSTER: Exfoliator
================================================================================

Cluster 0
Anti_Aging     1.00
Brightening    1.00
Large_Pores    0.99
Oily           0.96
Eczema         0.94
Dark_Spots     0.93
Name: 0, dtype: float64

Contoh produk:
            brand                                     name       type
      Dermalogica                       Daily Superfoliant Exfoliator
        Nip + Fab                       Glycolic Fix Scrub Exfoliator
           KORRES   Olive Stones Intense Exfoliating Scrub Exfoliator
  Victoria Beauty              AHA & BHA Blemish Out Toner Exfoliator
Eminence Organics Mangosteen Daily Resurfacing Concentrate Exfoliator

Cluster 1
Anti_Aging     1.00
Brightening    0.95
Scar           0.93
Large_Pores    0.26
Oily           0.24
Hydrating      0.21
Name: 1, dtype: float64

Contoh produk:
        brand                                  name       type
         ESPA                  Refining Skin Polish Exfoliator
NYX Cosmetics           #Thisiseverything Lip Scrub Exfoliator
        Sukin Super Greens Detoxifying Facial Scrub Exfoliator
       Neogen             Pore Tight Peeling Mousse Exfoliator
         MUSQ                   Radiate Face Polish Exfoliator

Cluster 2
Large_Pores     1.00
Brightening     1.00
Oily            0.99
Skin_Texture    0.99
Anti_Aging      0.99
Rosacea         0.98
Name: 2, dtype: float64

Contoh produk:
              brand                                                   name       type
Dr. Brandt Skincare Microdermabrasion Renewing Age-Defying Face Exfoliator Exfoliator
   Serious Skincare    Glycolic Gommage Extreme Renewal Exfoliating Facial Exfoliator
    Monroe Skincare                            Exfoliator & Pore Minimizer Exfoliator
            Alpha-H                    Liquid Gold Rose with Glycolic Acid Exfoliator
 Earth Therapeutics                          Charcoal Purifying Foot Scrub Exfoliator

Cluster 3
Eczema         0.20
Large_Pores    0.17
Redness        0.14
Brightening    0.14
Hydrating      0.13
Rosacea        0.12
Name: 3, dtype: float64

Contoh produk:
         brand                                                        name       type
    Neutrogena                       Deep Clean Invigorating Foaming Scrub Exfoliator
         Nivea                     Purify Bio Aloe Vera Organic Rice Scrub Exfoliator
      Himalaya                                Moisturizing Argan Oil Scrub Exfoliator
Formula 10.0.6                One Smooth Operator Pore Clearing Face Scrub Exfoliator
          Dove Men+Care Deep Clean + Facial Cleanser Exfoliating Face Wash Exfoliator

Cluster 4
Eczema         1.00
Rosacea        1.00
Large_Pores    0.97
Anti_Aging     0.95
Brightening    0.32
Redness        0.11
Name: 4, dtype: float64

Contoh produk:
                  brand                                          name       type
         Go-To Skincare                           Exfoliating Swipeys Exfoliator
          Clean & Clear Oil-Free Deep Action Exfoliating Facial Scrub Exfoliator
          Biba de Sousa                                Mandelic Scrub Exfoliator
Renee Rouleau Skin Care                  Triple Berry Smoothing Scrub Exfoliator
                 Elemis               Dynamic Resurfacing Facial Pads Exfoliator

Cluster 5
Redness         1.00
Skin_Texture    1.00
Dark_Spots      1.00
Anti_Aging      1.00
Brightening     0.84
Scar            0.32
Name: 5, dtype: float64

Contoh produk:
        brand                                              name       type
      Origins Modern Friction Nature's Gentle Microdermabrasion Exfoliator
       La Mer                   The Replenishing Oil Exfoliator Exfoliator
     Bee Bald                       Scrub Exfoliating Pre-Shave Exfoliator
The Body Shop             Vitamin C Daily Glow Cleansing Polish Exfoliator
       A'Pieu                       Naked Peeling Gel - Crystal Exfoliator

Cluster 6
Brightening      1.00
Acne_Fighting    0.96
Oily             0.94
Large_Pores      0.94
Eczema           0.93
Rosacea          0.21
Name: 6, dtype: float64

Contoh produk:
         brand                                          name       type
Paula's Choice       Skin Perfecting 2% BHA Liquid Exfoliant Exfoliator
      St. Ives               Acne Control Face Scrub Apricot Exfoliator
     Nip + Fab                           Salicylic Fix Scrub Exfoliator
 The Body Shop Tea Tree Squeaky-Clean Exfoliating Face Scrub Exfoliator
      Botanics                         All Bright Face Scrub Exfoliator

================================================================================
PROFIL CLUSTER: Makeup Remover
================================================================================

Cluster 0
Brightening    0.27
Large_Pores    0.23
Hydrating      0.10
Eczema         0.09
Oily           0.06
Redness        0.06
Name: 0, dtype: float64

Contoh produk:
        brand                                            name           type
      Lancôme       Bi-Facil Double-Action Eye Makeup Remover Makeup Remover
   Neutrogena Ultra Light Face Cleansing Oil & Makeup Remover Makeup Remover
The Face Shop               Rice Water Bright Cleansing Wipes Makeup Remover
Holika Holika             Daily Fresh Olive Lip & Eye Remover Makeup Remover
      L'Oreal              Dermo-Expertise Eye Makeup Remover Makeup Remover

Cluster 1
Large_Pores    0.91
Eczema         0.83
Rosacea        0.74
Brightening    0.71
Anti_Aging     0.69
Hydrating      0.20
Name: 1, dtype: float64

Contoh produk:

In [18]:
#cek file pkl sudah tersimpan belum
print("File model clustering yang tersimpan:")

for file in MODEL_DIR.glob("*.pkl"):
    print(file)

File model clustering yang tersimpan:
..\models\clustering\kmodes_exfoliator.pkl
..\models\clustering\kmodes_face_cleanser.pkl
..\models\clustering\kmodes_makeup_remover.pkl
..\models\clustering\kmodes_moisturizer.pkl
..\models\clustering\kmodes_serum.pkl
..\models\clustering\kmodes_sunscreen.pkl
..\models\clustering\kmodes_toner.pkl